### PR TITLE
add an early low memory error to GTNH

### PR DESCRIPTION
**Pull request by bombcar**
See https://discordapp.com/channels/181078474394566657/234936569360809996/926665005959622657

This will check and error out if the RAM is not enough. It defaults to 3GB (configurable) and works on server and client, throwing a nice message on client (forced it to 30GB to show):

image

The server-side message is not as pretty because I can't suppress the forge barf, but it shows:

```
[22:36:03] [main/DEBUG] [FML/]: Running coremod plugin for CodeChickenCorePlugin {codechicken.core.launch.CodeChickenCorePlugin}
[22:36:03] [main/DEBUG] [FML/]: Running coremod plugin CodeChickenCorePlugin
[22:36:03] [main/ERROR] [CodeChickenCore/]: You should have at least 30GB but you have allocated 6.0 GiB.
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ExceptionInInitializerError
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.systemCheck(CodeChickenCorePlugin.java:152)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.call(CodeChickenCorePlugin.java:189)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.call(CodeChickenCorePlugin.java:34)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:133)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 6 more
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.NullPointerException
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.<init>(Loader.java:198)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.instance(Loader.java:176)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.<init>(FMLCommonHandler.java:87)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.<clinit>(FMLCommonHandler.java:77)
[22:36:03] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 12 more
```

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]
Seems reasonable to me.  I might suggest adding that they can change the config if they _really_ want to try.

**Comment by mitchej123** [comment]
Oh, one other thing to be careful of; let's be sure _not_ to make NEI depend on this version.  I don't want this getting pulled into other modpacks....

**Comment by bombcar** [comment]
> Oh, one other thing to be careful of; let's be sure _not_ to make NEI depend on this version. I don't want this getting pulled into other modpacks....

Good point, I can make this do nothing if the config isn't set .... hmmm

**Comment by mitchej123** [comment]
As long as NEI doesn't automagically pull in this version, I don't care.  Or set it to 1gb by default and ship it with 3gb in our pack.

**Comment by glowredman** [comment]
It shouldn't, CF pulls CCC: https://www.curseforge.com/minecraft/mc-mods/notenoughitems/relations/dependencies. (@mitchej123  do you have set this too for your NEI version?

**Comment by mitchej123** [comment]
I think so?

I was more thinking of dependencies.json   I forget if that's handled in CCC or CCL... might be a non issue.

**Comment by bombcar** [comment]
Dependencies pulls CCL via CCC but doesn't update CCC (at this time, in theory it could).

**Comment by mitchej123** [comment]
Cough. @bombcar   needs to be off by default.  Dream merged before you addressed that

**Pull request merged**
