### PR TITLE
Bye bye DepLoader

### PR DESCRIPTION
**Pull request by mitchej123**
Bye bye DepLoader
* Gut DepLoader
* Merge in CCL

### CODE REVIEW

**Comment by Dream-Master** [comment]
@mitchej123 but the dep loader in the core mod is not affected ?

**Comment by Caedis** [comment]
Nah, dreamcraft does its own thing
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/coremod/DepLoader.java

**Comment by Caedis** [comment]
Issue in latest nightly (541)
[fml-client-latest.log](https://github.com/user-attachments/files/16081391/fml-client-latest.log)

**Comment by mitchej123** [comment]
> Issue in latest nightly (541) [fml-client-latest.log](https://github.com/user-attachments/files/16081391/fml-client-latest.log)

I ran this locally in the full pack and had no issues.  Do you by chance have two versions of CCC in the the mods dir?

**Comment by Caedis** [comment]
The test was with a fresh nightly instance directly imported from the zip

**Comment by mitchej123** [comment]
@Dream-Master Don't mergemaster this

**Comment by mitchej123** [comment]
> The test was with a fresh nightly instance directly imported from the zip

I see, it couldn't find CCL without deploader -- pushing the subtree merge....

**Comment by Caedis** [comment]
Going to close this pr and manually merge `--ff-only` to master?

**Comment by mitchej123** [comment]
> Going to close this pr and manually merge `--ff-only` to master?

Feel free to approve, I'll merge and push locally which should still close the PR

**Pull request merged**
