### PR TITLE
Change ASM dump folder

### PR DESCRIPTION
**Pull request by Alexdoru**
If two mods use the same class dumping folder it will erase the contents of the folder each time a transformer writes their first class. Therefore I change the name to a mod specific name

### CODE REVIEW

**Comment by Glease** [comment]
who else are we colliding with? besides, what's the reason for spotless:off?

**Comment by Alexdoru** [comment]
angelica had the same ASM dump folder name since it was just the same method getting copied over from mods to mods

I turned spotless off cause ASM is already hard to understand and spotless makes it unreadable

**Comment by Alexdoru** [comment]
so I changed the folder name to have the mod ID

**Review by Glease — APPROVED** [review]
it might be better to have a protocol for this (like a bool in launch blackboard telling others which debug output folder had been wiped or something).. but for now this works

**Pull request merged**
